### ISSUE TITLE
 После установки не изменена иконка мульти инсталера и не изменены названия на CloudClient

### ISSUE THREAD

**Issue by LafayetteGPool** [W3dCIoud/CloudClient#2]
![Снимок экрана 2023-12-20 151914](https://github.com/W3dCIoud/CloudClient/assets/88727912/0db8a2b7-d964-4fdc-8b94-74853ffb2da5)

**Comment by W3dCIoud** [comment]
Прости что пишу так поздно)
Баг исправлен. Спасибо!
